name: Commons

author: kodirati
website: kodirati.com
description: Used as the library for the servers of Evil Kingdom.

main: net.evilkingdom.commons.Commons
version: 1.0
api-version: 1.18
depend: [FastAsyncWorldEdit, spark, LuckPerms]

commands: